MAX_SIZE_DEFAULT_INPUT_TEXT = 255
DEFAULT_NAME_REGEX = /\A[a-zA-Z\s\-']+\z/
PATH_FAKE_FILES = Rails.root.join('spec', 'fake_files')

# USER
MIN_SIZE_USER_PASSWORD = 6
MAX_SIZE_USER_PASSWORD = 15
MAX_SIZE_USER_FIRST_NAME = 50
MAX_SIZE_USER_LAST_NAME = 50
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

# JOB
MIN_SIZE_JOB_NAME = 5

# COUNTRY
SIZE_COUNTRY_CODE = 2
MIN_SIZE_COUNTRY_NAME = 3

# CONTACT
MIN_SIZE_CONTACT_FIRST_NAME = 2
MAX_SIZE_CONTACT_FIRST_NAME = 50
MIN_SIZE_CONTACT_LAST_NAME = 2
MAX_SIZE_CONTACT_LAST_NAME = 50
MAX_SIZE_CONTACT_COMMENT = 500
# UPLOAD
MAX_SIZE_CONTACT_PHOTO = 2.megabytes
UPLOAD_PATH_CONTACT_PHOTO = Rails.root.join('public', 'upload', 'contact', 'photo').to_s
ROWS_IMG_CONTACT_PHOTO = 100
COLS_IMG_CONTACT_PHOTO = 100